version: "3"
services:
  client:
    image: client-production:local
    build: ./frontend/
    stdin_open: true
    ports:
      - "4000:4000"
    networks:
      - live-chat
    volumes:
      - ./frontend:/app
      - /app/node_modules
  server:
    image: server
    build: ./backend/
    ports:
      - "3000:3000"
    networks:
      - live-chat
    volumes:
        - ./backend:/app
        - /app/node_modules


  nginx:
    restart: always
    depends_on:
      - server
      - client
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "8080:80"
    networks:
      - live-chat
networks:
    live-chat:
        driver: bridge

